name = "TropicalSteadyStateBounds"
uuid = "711c507e-943e-4fde-96e1-c888ddd1de7d"
version = "0.1.0"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
MixedSubdivisions = "291d046c-3347-11e9-1e74-c3d251d406c6"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Documenter", "Random"]
